name: cff-validator
author: Diego Hernangómez
description: "Validate your repository's CITATION.cff file using R software"
branding:
  icon: 'book-open'
  color: 'gray-dark'
inputs:
  citation-path:
    description: 'Path to .cff file to be validated. By default it selects a CITATION.cff file on the root of the repository.'
    required: false
    default: 'CITATION.cff'
  cache-version:
    description: 'Soft deprecated'
    required: false
    default: 1
  install-r:
    description: 'Soft deprecated'
    required: false
    default: true
# pak cache management derived from https://github.com/r-lib/actions/blob/v2-branch/setup-r-dependencies/action.yaml
# By Jim Hester
runs:
  using: composite
  steps:
    - name: Validate cff
      uses: dieghernan/cff-validator/docker@dev
      with:
        cffpath: "${{ inputs.citation-path }}"

      # Report check
    - name: Upload results
      shell: bash
      run: |
        # Upload results
        cat citation_cff.md >$GITHUB_STEP_SUMMARY

    - name: Check for errors
      id: err
      shell: bash
      run: |
        # Identify errors
        err=false
        if test -f "issue.md"; then
          err=true
        fi
        echo "error=$err" >> $GITHUB_OUTPUT

    - name: Fail workflow
      if: steps.err.outputs.error == 'true'
      shell: bash
      run: |
        echo "::error:: ${{ github.event.client_payload.citation-path }} has errors, see Job Summary"
        exit 1

