name: cff-validator
author: Diego Hernangómez
description: "Validate your repository's CITATION.cff file using R software"
branding:
  icon: 'book-open'
  color: 'gray-dark'
inputs:
  citation-path:
    description: 'Path to .cff file to be validated. By default it selects a CITATION.cff file on the root of the repository.'
    required: false
    default: 'CITATION.cff'
  cache-version:
    description: 'The version of the cache, change this from the default (1) to start over with a fresh cache.'
    required: false
    default: 1
  install-r:
    description: 'Soft deprecated, needs to be always installed'
    required: false
    default: true
# pak cache management derived from https://github.com/r-lib/actions/blob/v2-branch/setup-r-dependencies/action.yaml
# By Jim Hester
runs:
  using: composite
  steps:
    - name: Validate cff
      uses: dieghernan/cff-validator/docker@dev
      with:
        cffpath: "${{ inputs.citation-path }}"
