name: cff-validator
author: Diego Hernangómez
description: "Validate your repository's CITATION.cff file using R software"
branding:
  icon: 'book-open'
  color: 'gray-dark'
inputs:
  citation-path:
    description: 'Path to .cff file to be validated. By default it selects a
      CITATION.cff file on the root of the repository.'
    required: false
    default: 'CITATION.cff'
  cache-version:
    description: 'Soft deprecated'
    required: false
    default: 1
  install-r:
    description: 'Soft deprecated'
    required: false
    default: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
  - ${{ inputs.citation-path }}
