on:
  push:
    branches:
      - main
  workflow_dispatch:

name: CITATION.cff-complete
jobs:
  Validate-CITATION-cff-complete:
    runs-on: ubuntu-latest
    name: Validate CITATION.cff
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate examples/key-complete/CITATION.cff
        uses: dieghernan/cff-validator@main
        with:
          citation-path: "./examples/key-complete/CITATION.cff"

