on:
  push:
    branches:
    - main
  workflow_dispatch:


name: CITATION.cff-tests
permissions:
  contents: write
jobs:
  Validate-CITATION-cff-tests:
    runs-on: ubuntu-latest
    name: Validate CITATION.cff
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Validate examples/key-tests/CITATION_languages.cff
      uses: dieghernan/cff-validator@main
      with:
        citation-path: "./examples/key-tests/CITATION_languages.cff"
